spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: root
    password: 9DbqDeR^zT$x&W8v
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    gateway:
      mvc:
        routes:
        - id: battle-service
          uri: lb://battle-service
          predicates:
            - Path=/battle/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: tournament-service
          uri: lb://tournament-service
          predicates:
            - Path=/tournament/**
  application:
    name: api-gateway

application:
  security:
    jwt:
      secret-key: ab59ff52534a5b8f83b52fec82228eba79a991829b25bc4482c01ee04d54727e
      expiration: 864000000 # 10 days
      refresh-token:
        expiration: 604800000 # 7 days


logging:
  level:
    root: WARN
    com.polimi.ckb.battleService: DEBUG

server:
  port: 8080
