spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: root
    password: 123Stella!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    gateway:
      mvc:
        routes:
        - id: battle-service
          uri: lb://battle-service
          predicates:
            - Path=/battle/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: tournament-service
          uri: lb://tournament-service
          predicates:
            - Path=/tournament/**
  application:
    name: api-gateway


logging:
  level:
    root: WARN
    com.polimi.ckb.battleService: DEBUG

server:
  port: 8080
