

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: root
    password: 9DbqDeR^zT$x&W8v
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

  cloud:
    gateway:
      mvc:
        routes:
        - id: battle-service
          uri: http://localhost:8081
          predicates:
            - Path=/battle/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: tournament-service
          uri: http://localhost:8083
          predicates:
            - Path=/tournament/**

logging:
  level:
    root: WARN
    com.polimi.ckb.battleService: DEBUG
server:
  port: 8080