spring:
  datasource:
    url: jdbc:mysql://localhost:3307/authentication
    username: root
    password: pw
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
  cloud:
    gateway:
      mvc:
        routes:
        - id: battle-service
          uri: lb://battle-service
          predicates:
            - Path=/battle/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: tournament-service
          uri: lb://tournament-service
          predicates:
            - Path=/tournament/**
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8080