spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: battle-service
          uri: http://localhost:8081
          predicates:
            - Path=/battle/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: tournament-service
          uri: http://localhost:8083
          predicates:
            - Path=/tournament/**

logging:
  level:
    root: WARN
    com.polimi.ckb.battleService: DEBUG