name: Notify on Push

on:
  push:
    branches:
      - 'master'

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTML notification
        run: |
          - curl -X POST \
          - -H "Content-Type: application/json" \
          - -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
          - -d '{"token":"${{ secrets.GIT_TOKEN }}","name":"${{ secrets.GIT_NAME}}","html_url":"https://github.com/${{ github.repository }}/commit/${{ github.sha }}"}' \
          - https://your-service-address/battle/score
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}